project_id = "glgocjuwmssnaztljdus"

[functions.edrion-analyze]
verify_jwt = false

[functions.edrion-save-result]
verify_jwt = false

[functions.auto-confirm-user]
verify_jwt = false

[functions.edrion-hotmart-webhook]
verify_jwt = false
