import { supabase } from "@/integrations/supabase/client";
import type { AnalysisResult } from "@/types/analysis";
import type { ShowcaseProfile } from "@/components/ShowcaseCarousel";

/**
 * Fetch a cached showcase analysis from the database.
 * If not found, builds a complete demo result with real data.
 * Showcase analyses show FULL free-tier content (bio analysis, raio-x,
 * post metrics, strengths/improvements) to demonstrate value.
 * Only premium content (weekly plan, stories, full post analysis) stays locked.
 */
export async function fetchShowcaseResult(
  profile: ShowcaseProfile,
): Promise<AnalysisResult> {
  try {
    const { data } = await supabase
      .from("analysis_result")
      .select("result_json")
      .eq("handle", profile.handle)
      .order("created_at", { ascending: false })
      .limit(1)
      .single();

    if (data?.result_json) {
      const result = data.result_json as unknown as AnalysisResult;
      return { ...result, plan: "free" };
    }
  } catch {
    // No saved analysis — use pre-populated demo
  }

  return buildShowcaseResult(profile);
}

/* ─── Complete pre-populated data per profile ───────────────── */

interface ProfileShowcase {
  bio: string;
  following: number;
  posts_count: number;
  // Bio analysis
  bio_score: number;
  bio_score_new: number;
  suggested_bio: string;
  rationale: string;
  cta_option: string;
  criteria: { clarity: number; authority: number; cta: number; seo: number; brand_voice: number; specificity: number };
  criteria_new: { clarity: number; authority: number; cta: number; seo: number; brand_voice: number; specificity: number };
  // Raio-X da Bio (diagnostic)
  proposta_valor: string;
  segmentacao_publico: string;
  gatilhos_autoridade: string;
  cta_conversao: string;
  seo_instagram: string;
  tom_de_voz: string;
  // Strengths & improvements
  strengths: string;
  improvements: string;
  // Top post
  top_caption: string;
  top_likes: number;
  top_comments: number;
  top_views: number;
  top_engagement: number;
  top_score: number;
  top_resumo: string;
  top_positivos: string[];
  top_negativos: string[];
  top_gancho: string;
  top_legenda: string;
  top_formato: string;
  top_hashtags: string;
  top_rubrica: { gancho: number; legenda: number; formato: number; engajamento: number; estrategia: number };
  top_recomendacoes: string[];
  // Worst post
  worst_caption: string;
  worst_likes: number;
  worst_comments: number;
  worst_views: number;
  worst_engagement: number;
  worst_score: number;
  worst_resumo: string;
  worst_positivos: string[];
  worst_negativos: string[];
  worst_gancho: string;
  worst_legenda: string;
  worst_formato: string;
  worst_hashtags: string;
  worst_rubrica: { gancho: number; legenda: number; formato: number; engajamento: number; estrategia: number };
  worst_recomendacoes: string[];
  // Next post suggestion
  next_format: string;
  next_hook: string;
  next_outline: string[];
  next_cta: string;
  next_angle: string;
}

const PROFILES: Record<string, ProfileShowcase> = {
  bianca: {
    bio: "nada e tao nosso quanto os nossos sonhos\n@bocarosabeauty\n@bocarosacompany",
    following: 2_932,
    posts_count: 8_195,
    bio_score: 5.8,
    bio_score_new: 8.5,
    suggested_bio: "CEO da Boca Rosa Company | Transformando beleza em negócio 💄\nMãe do Cris 💛 | De influenciadora a empresária\n🛍 Conheça a Boca Rosa ↓",
    rationale: "A bio atual é poética mas não comunica proposta de valor, não tem CTA e não menciona a autoridade empresarial. Um visitante novo não entende o que Bianca faz. A sugestão mantém a autenticidade mas adiciona posicionamento claro + CTA.",
    cta_option: "Conheça a Boca Rosa ↓",
    criteria: { clarity: 2, authority: 2, cta: 1, seo: 2, brand_voice: 4, specificity: 2 },
    criteria_new: { clarity: 5, authority: 5, cta: 4, seo: 4, brand_voice: 5, specificity: 4 },
    proposta_valor: "A bio não comunica proposta de valor. 'Nada é tão nosso quanto os nossos sonhos' é inspiracional mas genérica — poderia ser de qualquer perfil. O visitante não entende se Bianca é influenciadora, empresária ou artista.",
    segmentacao_publico: "Sem segmentação visível. A bio não indica para quem é o conteúdo: empreendedoras, consumidoras de beleza, aspirantes a influenciadoras? O público-alvo fica indefinido.",
    gatilhos_autoridade: "Menciona @bocarosabeauty e @bocarosacompany mas sem contexto de escala (faturamento 8 dígitos, presente em +30K pontos de venda). Perde oportunidade de gerar admiração.",
    cta_conversao: "Não há CTA. Nenhum link, nenhum direcionamento. O visitante não sabe o que fazer depois de ler a bio. Taxa de clique no link da bio provavelmente abaixo de 1%.",
    seo_instagram: "Não usa keywords de busca. Termos como 'maquiagem', 'empreendedora' ou 'beleza brasileira' ajudariam na descoberta via search do Instagram.",
    tom_de_voz: "Tom poético e autêntico — combina com a marca pessoal. Esse é o ponto forte da bio. Porém, precisa equilibrar emoção com informação prática.",
    strengths: "Marca pessoal extremamente forte. Storytelling autêntico que gera conexão emocional. Transição bem-sucedida de influenciadora para CEO de empresa bilionária. Brand voice consistente e reconhecível.",
    improvements: "Bio sem CTA direto para conversão — visitantes não sabem o que fazer. Poucos posts educativos sobre empreendedorismo que engajariam a audiência aspiracional. Taxa de engajamento de 0.86% está abaixo da média para o tamanho da conta (esperado ~1.5%).",
    top_caption: "Quando eu comecei a Boca Rosa Company todo mundo falou que não ia dar certo. Eu tinha 22 anos, zero experiência em negócios e um sonho que não cabia em mim. Hoje a gente fatura 8 dígitos por ano e tá em mais de 30 mil pontos de venda. Se você tem um sonho que parece grande demais, esse post é pra você. 💛",
    top_likes: 430_000,
    top_comments: 26_800,
    top_views: 5_800_000,
    top_engagement: 2.85,
    top_score: 8.6,
    top_resumo: "Post com storytelling pessoal de superação que gera identificação massiva. O gancho 'todo mundo falou que não ia dar certo' ativa curiosidade e empatia. Números concretos (8 dígitos, 30K PDVs) funcionam como prova social. O CTA emocional no final ('se você tem um sonho') transforma o post em algo compartilhável.",
    top_positivos: ["Gancho de superação que gera curiosidade imediata", "Números concretos que provam autoridade (8 dígitos, 30K PDVs)", "Storytelling pessoal e autêntico com arco narrativo completo", "CTA emocional que incentiva compartilhamento"],
    top_negativos: ["Poderia incluir um CTA mais direto (comentar, salvar)", "Sem hashtags estratégicas para ampliar alcance orgânico"],
    top_gancho: "Excelente. 'Todo mundo falou que não ia dar certo' é um gancho de conflito que ativa curiosidade. O leitor quer saber o desfecho. Padrão de storytelling que funciona em qualquer nicho.",
    top_legenda: "Estrutura narrativa perfeita: situação inicial (22 anos, zero experiência) → conflito (descrença alheia) → resolução (faturamento 8 dígitos). Linguagem acessível e emotiva. Tamanho ideal para engajamento.",
    top_formato: "Carrossel com fotos pessoais funciona muito bem para storytelling. O formato permite ao algoritmo mais tempo de visualização por swipe, aumentando a distribuição.",
    top_hashtags: "Sem hashtags visíveis neste post — para contas com +19M, hashtags têm impacto mínimo. A distribuição vem do engajamento direto (likes, comments, shares).",
    top_rubrica: { gancho: 5, legenda: 5, formato: 4, engajamento: 5, estrategia: 4 },
    top_recomendacoes: ["Adicionar CTA direto no final: 'Salve esse post se você precisa dessa energia' aumentaria os salvamentos em ~40%", "Replicar este formato de storytelling pessoal 2x por semana — é o tipo de conteúdo que mais performa", "Usar a mesma estrutura (conflito → superação → números) para posts sobre a Boca Rosa Company"],
    worst_caption: "Domingão de sol ☀️ #domingo #lifestyle",
    worst_likes: 80_600,
    worst_comments: 4_100,
    worst_views: 1_500_000,
    worst_engagement: 0.56,
    worst_score: 3.2,
    worst_resumo: "Post genérico sem contexto narrativo. 'Domingão de sol' não agrega valor, não gera curiosidade e não incentiva interação. Engajamento 70% abaixo da média do perfil. Hashtags genéricas (#domingo #lifestyle) não atraem público qualificado.",
    worst_positivos: ["Foto com boa qualidade visual e iluminação natural"],
    worst_negativos: ["Caption genérica sem nenhum gancho ou storytelling", "Hashtags irrelevantes que não atraem público-alvo", "Sem CTA — não pede interação nenhuma", "Não se conecta com o posicionamento de empreendedora/empresária"],
    worst_gancho: "Inexistente. 'Domingão de sol' é o oposto de um gancho — não gera curiosidade, não provoca emoção e não dá motivo para parar o scroll. O algoritmo penaliza posts que não retêm atenção nos primeiros 3 segundos.",
    worst_legenda: "Uma frase genérica que poderia ser de qualquer pessoa. Não tem personalidade, não conta história, não agrega valor. Para uma conta de 19M, isso é desperdiçar alcance potencial.",
    worst_formato: "Foto única estática com caption curta. Para o algoritmo atual do Instagram (2025-2026), fotos únicas sem contexto têm ~50% menos distribuição que Reels ou carrosseis.",
    worst_hashtags: "#domingo e #lifestyle são hashtags extremamente saturadas (centenas de milhões de posts). Nenhuma relação com o nicho de empreendedorismo ou beleza. Zero impacto no alcance.",
    worst_rubrica: { gancho: 1, legenda: 1, formato: 2, engajamento: 1, estrategia: 1 },
    worst_recomendacoes: ["Mesmo posts casuais precisam de contexto: 'Domingão de sol recarregando as energias pra semana que vem — segunda tem lançamento novo da Boca Rosa 👀'", "Substituir hashtags genéricas por nichadas: #empreendedorismodigital #bocarosa #belezabrasileira", "Adicionar pergunta no final para gerar comentários: 'O que vocês fazem pra recarregar no domingo?'"],
    next_format: "Reels",
    next_hook: "O erro que me custou R$2 milhões no primeiro ano da Boca Rosa",
    next_outline: ["Abrir com o erro (comprou estoque demais sem validar demanda)", "Mostrar a consequência real (quase quebrou)", "Revelar o que aprendeu (testar pequeno antes de escalar)", "Conectar com a audiência (você já cometeu esse erro?)"],
    next_cta: "Comenta ERRO se você já passou por algo parecido",
    next_angle: "Storytelling de negócios com vulnerabilidade",
  },

  "thiago.nigro": {
    bio: "Primo Rico | Investimentos\n+10M de pessoas educadas financeiramente\nAutor best-seller 'Do Mil ao Milhão'\n📖 Novo livro ↓",
    following: 2_188,
    posts_count: 3_299,
    bio_score: 7.5,
    bio_score_new: 9.2,
    suggested_bio: "Primo Rico | Já ajudei +10M de pessoas a investir melhor 💰\nAutor best-seller 'Do Mil ao Milhão'\nSeu próximo passo financeiro começa aqui ↓",
    rationale: "A bio já tem autoridade forte com o número de 10M de alunos. Pode melhorar com um CTA mais orientado à ação e reforçar a transformação que o seguidor terá.",
    cta_option: "Seu próximo passo financeiro começa aqui ↓",
    criteria: { clarity: 4, authority: 5, cta: 3, seo: 3, brand_voice: 4, specificity: 4 },
    criteria_new: { clarity: 5, authority: 5, cta: 5, seo: 4, brand_voice: 5, specificity: 5 },
    proposta_valor: "Clara e forte — 'investimentos' define o nicho instantaneamente. O número '+10M educadas' posiciona como líder absoluto do segmento no Brasil.",
    segmentacao_publico: "Implícita mas eficaz. Quem procura educação financeira no Instagram encontra o posicionamento certo. Poderia ser mais específico sobre o nível (iniciantes vs avançados).",
    gatilhos_autoridade: "Excelentes: best-seller, +10M de pessoas, marca 'Primo Rico' reconhecida nacionalmente. O livro funciona como prova social tangível.",
    cta_conversao: "Tem CTA mas genérico ('Novo livro ↓'). Poderia ser mais orientado a ação transformacional: 'Comece a investir hoje ↓' seria mais eficaz.",
    seo_instagram: "Usa 'Investimentos' que é um keyword forte. Faltam variações como 'finanças pessoais', 'renda fixa', 'como investir' que ampliariam a descoberta.",
    tom_de_voz: "Profissional e acessível — exatamente o tom que funciona para educação financeira. Não é intimidador nem superficial. Equilibra autoridade com proximidade.",
    strengths: "Autoridade inquestionável no nicho de finanças. Conteúdo educativo de altíssima qualidade com ganchos numéricos que geram curiosidade. Marca pessoal 'Primo Rico' é sinônimo de educação financeira no Brasil.",
    improvements: "Engajamento de 0.69% está baixo para o tamanho da conta — excesso de conteúdo pode diluir. Posts muito genéricos sobre lifestyle performam mal comparado ao educativo. Focar em menos posts por semana com mais profundidade.",
    top_caption: "Se você ganha R$3.000 por mês e fizer ISSO aqui, em 5 anos você tem R$100 mil guardados. Parece impossível? Faz a conta comigo:\n\nPasso 1: Separe 20% do salário (R$600)\nPasso 2: Invista em renda fixa a 12% ao ano\nPasso 3: Reinvista os juros TODO mês\n\nResultado: R$600/mês × 60 meses + juros compostos = R$102.347\n\nVocê não precisa ganhar mais. Você precisa INVESTIR melhor. Salva esse post. 💰",
    top_likes: 285_000,
    top_comments: 18_500,
    top_views: 8_200_000,
    top_engagement: 3.72,
    top_score: 9.1,
    top_resumo: "Post educativo com gancho numérico irresistível. A promessa concreta (R$100K em 5 anos ganhando R$3K) é específica o suficiente para ser crível e aspiracional o suficiente para gerar interesse. Estrutura passo a passo aumenta salvamentos. CTA 'Salva esse post' é eficaz.",
    top_positivos: ["Gancho numérico específico que gera curiosidade imediata", "Passo a passo prático que aumenta taxa de salvamento", "Números reais e verificáveis geram credibilidade", "CTA direto e relevante ('Salva esse post')"],
    top_negativos: ["Poderia incluir disclaimer sobre rentabilidade passada", "Formato de texto longo pode perder audiência visual — carrossel seria mais eficaz"],
    top_gancho: "'Se você ganha R$3.000' — gancho de identificação imediata. Boa parte da audiência se identifica com esse valor. 'Parece impossível?' cria loop de curiosidade.",
    top_legenda: "Estrutura didática perfeita: premissa → passos → resultado. Linguagem simples sem jargão financeiro. O cálculo concreto transforma abstrato em tangível.",
    top_formato: "Reels com texto na tela funcionaria ainda melhor que apenas legenda. Mas mesmo como post de texto, a estrutura em lista facilita a leitura e incentiva salvamento.",
    top_hashtags: "Hashtags nichadas como #investimentos #educacaofinanceira #rendafixa teriam bom impacto. Para o tamanho da conta, o alcance orgânico já é forte sem hashtags.",
    top_rubrica: { gancho: 5, legenda: 5, formato: 4, engajamento: 5, estrategia: 5 },
    top_recomendacoes: ["Transformar em carrossel com 1 passo por slide para aumentar tempo de retenção", "Criar série 'Se você ganha X...' com diferentes faixas salariais", "Adicionar 'Manda pro amigo que precisa ouvir isso' como segundo CTA"],
    worst_caption: "Foto do escritório novo 📸 #office #primorico",
    worst_likes: 42_000,
    worst_comments: 2_100,
    worst_views: 1_200_000,
    worst_engagement: 0.43,
    worst_score: 2.8,
    worst_resumo: "Post completamente desconectado do posicionamento. O público segue Thiago para aprender a investir, não para ver escritórios. Zero valor educativo, zero gancho, zero CTA. Engajamento 38% abaixo da média.",
    worst_positivos: ["Boa qualidade visual da foto"],
    worst_negativos: ["Sem valor educativo — o público não segue para ver escritórios", "Caption genérica de 5 palavras que não gera interação", "Hashtags irrelevantes (#office) fora do nicho", "Desperdiça alcance que poderia educar a audiência"],
    worst_gancho: "Inexistente. 'Foto do escritório novo' não gera curiosidade. Se fosse 'O escritório custou R$2M — e eu paguei à vista. Te conto como.' seria completamente diferente.",
    worst_legenda: "5 palavras genéricas. Para o maior educador financeiro do Brasil, isso é subaproveitamento total. Cada post é uma oportunidade de impactar milhões.",
    worst_formato: "Foto estática de ambiente. Formato com menor distribuição no algoritmo atual. Carrossel ou Reels com tour do escritório + lições de negócio performaria 5x mais.",
    worst_hashtags: "#office é hashtag em inglês, desconectada do público brasileiro. #primorico é branded mas saturada pela própria conta.",
    worst_rubrica: { gancho: 1, legenda: 1, formato: 2, engajamento: 1, estrategia: 1 },
    worst_recomendacoes: ["Mesmo posts pessoais precisam de gancho educativo: 'Esse escritório custou X. Há 5 anos eu trabalhava na mesa da sala.'", "Nunca postar foto estática sem contexto narrativo — sempre conectar ao posicionamento", "Substituir por tour em Reels mostrando o escritório + 3 lições do que aprendeu construindo o Grupo Primo"],
    next_format: "Carrossel",
    next_hook: "5 investimentos que vão pagar mais que a poupança em 2026",
    next_outline: ["Slide 1: Gancho — 'Seu dinheiro está perdendo valor na poupança'", "Slides 2-6: Um investimento por slide com rentabilidade real", "Slide 7: Comparativo visual poupança vs investimentos", "Slide 8: CTA para salvar e compartilhar"],
    next_cta: "Salva esse carrossel e manda pro amigo que ainda deixa dinheiro na poupança 💰",
    next_angle: "Educativo com dados reais e comparativos",
  },

  francinyehlke: {
    bio: "@franbyfr\nfr@grupozenix.com",
    following: 590,
    posts_count: 1_900,
    bio_score: 3.2,
    bio_score_new: 8.0,
    suggested_bio: "Atriz, criadora de conteúdo e mãe da Céu 🤍\nBeleza real, sem filtro e com muito humor\n💄 @franbyfr | Forbes Under 30\n💌 Parcerias ↓",
    rationale: "Bio extremamente vazia — apenas o arroba da marca e e-mail de contato. Um visitante novo não sabe quem é Franciny, o que ela faz ou por que seguir. A sugestão constrói identidade completa.",
    cta_option: "💌 Parcerias ↓",
    criteria: { clarity: 1, authority: 1, cta: 1, seo: 1, brand_voice: 2, specificity: 1 },
    criteria_new: { clarity: 5, authority: 4, cta: 4, seo: 4, brand_voice: 5, specificity: 4 },
    proposta_valor: "Inexistente. A bio só tem o @ da marca e um e-mail. Não diz quem é, o que faz, ou por que alguém deveria seguir. Para 18.7M de seguidores, isso é um desperdício enorme.",
    segmentacao_publico: "Zero segmentação. Não menciona beleza, lifestyle, maternidade ou qualquer tema. O público não sabe o que esperar do conteúdo.",
    gatilhos_autoridade: "Nenhum gatilho de autoridade visível. Não menciona Forbes Under 30, números de seguidores, parcerias com marcas ou carreira de atriz.",
    cta_conversao: "O e-mail fr@grupozenix.com funciona como CTA para marcas, mas não para seguidores. Sem link, sem direcionamento para conteúdo.",
    seo_instagram: "Zero SEO. Sem keywords de busca. Termos como 'beleza', 'maquiagem', 'lifestyle' ou 'atriz' não aparecem em nenhum lugar.",
    tom_de_voz: "Minimalista ao extremo. Pode ser intencional (estética clean) mas sacrifica funcionalidade por estilo.",
    strengths: "Autenticidade e humor nos vídeos criam conexão forte com público feminino jovem. Conteúdo de beleza prático e acessível. Base de seguidores massiva e engajada.",
    improvements: "Bio completamente vazia perde milhares de potenciais seguidores diariamente. Engajamento de 1.52% é bom mas poderia ser maior com CTAs consistentes nos posts. Stories poderiam direcionar mais para vendas da @franbyfr.",
    top_caption: "Tutorial de make que eu uso TODOS OS DIAS. 5 minutos e você sai pronta pra qualquer coisa. Salva esse vídeo! 💄\n\nProdutos:\n✨ Base @franbyfr (cor 03)\n✨ Corretivo líquido\n✨ Blush cremoso rosé\n✨ Máscara de cílios\n✨ Gloss nude\n\nSimples assim. Sem frescura. 5 passos. 5 minutos. Done.",
    top_likes: 520_000,
    top_comments: 31_000,
    top_views: 12_000_000,
    top_engagement: 3.85,
    top_score: 8.8,
    top_resumo: "Tutorial rápido e prático que resolve um problema real do público (make do dia a dia em 5 minutos). O gancho 'TODOS OS DIAS' gera curiosidade sobre a rotina da influencer. Lista de produtos facilita replicação. CTA 'Salva esse vídeo' impulsiona a métrica de salvamento que o algoritmo prioriza.",
    top_positivos: ["Resolve problema real: make rápida para o dia a dia", "Gancho de rotina pessoal gera curiosidade", "Lista de produtos facilita replicação", "CTA claro para salvamento"],
    top_negativos: ["Poderia mencionar tipo de pele para segmentar melhor", "Falta pergunta no final para gerar comentários"],
    top_gancho: "'Tutorial que eu uso TODOS OS DIAS' — revela rotina pessoal, o que sempre gera interesse. 'Pronta pra qualquer coisa em 5 minutos' dá promessa específica e alcançável.",
    top_legenda: "Estrutura eficiente: promessa → lista de produtos → reforço da simplicidade. Linguagem casual e acessível. Tamanho ideal — não é longa demais.",
    top_formato: "Reels tutorial — formato com maior distribuição no Instagram para conteúdo de beleza. Duração curta (5 minutos de tutorial condensados) mantém retenção alta.",
    top_hashtags: "Sem hashtags visíveis. Para conta desse tamanho, a distribuição é orgânica pelo engajamento. Hashtags teriam impacto marginal.",
    top_rubrica: { gancho: 5, legenda: 4, formato: 5, engajamento: 5, estrategia: 4 },
    top_recomendacoes: ["Criar série semanal 'Make em 5 minutos' com variações (trabalho, festa, casual)", "Adicionar pergunta: 'Qual próxima make vocês querem ver?' para gerar comentários", "Fixar esse tipo de conteúdo no perfil como post fixado"],
    worst_caption: "Look do dia ✨ #ootd #fashion",
    worst_likes: 95_000,
    worst_comments: 3_200,
    worst_views: 2_100_000,
    worst_engagement: 0.65,
    worst_score: 2.9,
    worst_resumo: "Post genérico sem nenhum diferencial. 'Look do dia' é um dos formatos mais saturados do Instagram. Sem contexto sobre as peças, marca, ocasião ou dica de moda. Engajamento 57% abaixo da média.",
    worst_positivos: ["Foto com boa produção visual e iluminação"],
    worst_negativos: ["Formato 'look do dia' é extremamente saturado", "Caption de 4 palavras não gera interação", "Hashtags em inglês (#ootd) desconectadas do público brasileiro", "Não menciona marcas, preços ou onde comprar"],
    worst_gancho: "Inexistente. 'Look do dia' é o anti-gancho — o scroll continua sem parar. Alternativa: 'Gastei R$89 nesse look inteiro — e parece que custou 10x mais'.",
    worst_legenda: "Quatro palavras. Para 18.7M de seguidores, cada post é uma oportunidade de impactar milhões. Caption genérica desperdiça esse potencial.",
    worst_formato: "Foto estática de look completo. Menor distribuição no algoritmo. Get Ready With Me em Reels com a mesma roupa performaria 4x mais.",
    worst_hashtags: "#ootd e #fashion são hashtags globais extremamente saturadas. Zero conexão com o público brasileiro de beleza e lifestyle.",
    worst_rubrica: { gancho: 1, legenda: 1, formato: 2, engajamento: 1, estrategia: 1 },
    worst_recomendacoes: ["Transformar looks em Reels 'Get Ready With Me' com narração e dicas", "Adicionar preços e onde comprar gera salvamentos e interação", "Trocar 'Look do dia' por gancho como: 'Essa combinação de cores que ninguém faz — mas deveria'"],
    next_format: "Reels",
    next_hook: "3 erros de make que te envelhecem 10 anos (e como corrigir)",
    next_outline: ["Mostrar cada erro na prática (excesso de base, sobrancelha errada, blush mal posicionado)", "Corrigir cada um ao vivo com técnica simples", "Before/after de cada correção", "Revelar o resultado final"],
    next_cta: "Comenta qual erro você comete e eu faço um tutorial específico 💄",
    next_angle: "Educativo com transformação visual",
  },

  camilacoutinho: {
    bio: "Founder @garotasestupidas & @iconoclastsbr\nAuthor of #ESTUPIDAEU\nYouTube.com/garotasestupidas\nForbes 30 under 30",
    following: 4_635,
    posts_count: 7_653,
    bio_score: 7.0,
    bio_score_new: 8.8,
    suggested_bio: "Pioneira da moda digital no Brasil desde 2006 🇧🇷\nFounder @garotasestupidas & @iconoclastsbr\n📚 Autora #ESTUPIDAEU | Forbes 30 Under 30\n✨ Tendências e lifestyle ↓",
    rationale: "Bio tem boa autoridade mas não comunica o diferencial histórico de ser a primeira blogueira de moda do Brasil. Adicionar essa prova temporal gera admiração instantânea.",
    cta_option: "✨ Tendências e lifestyle ↓",
    criteria: { clarity: 3, authority: 4, cta: 2, seo: 3, brand_voice: 3, specificity: 3 },
    criteria_new: { clarity: 5, authority: 5, cta: 4, seo: 4, brand_voice: 5, specificity: 5 },
    proposta_valor: "Parcialmente clara. Menciona projetos mas não o diferencial pessoal. 'Founder' em inglês pode confundir parte do público brasileiro.",
    segmentacao_publico: "Implícita via @garotasestupidas — quem conhece, entende. Mas novos visitantes não identificam o nicho imediatamente.",
    gatilhos_autoridade: "Bons: Forbes 30 under 30, autora de livro, fundadora de duas marcas. Poderia reforçar o pioneirismo (20 anos no mercado digital).",
    cta_conversao: "Link para YouTube presente mas sem CTA ativo. Não direciona o visitante a uma ação específica.",
    seo_instagram: "Faltam keywords em português como 'moda', 'tendências', 'lifestyle'. Termos em inglês ('Founder', 'Author') prejudicam SEO brasileiro.",
    tom_de_voz: "Sofisticado e internacional. Combina com o posicionamento de moda de alto nível, mas pode parecer distante para parte da audiência.",
    strengths: "Credibilidade de quase 20 anos no mercado digital de moda. Curadoria refinada e opinião respeitada. Público fiel de alto poder aquisitivo. Forbes 30 under 30 é prova social forte.",
    improvements: "Engajamento de 0.79% está abaixo da média para 2.4M de seguidores. Formato foto estática é predominante — Reels curtos com trends de moda têm 3x mais alcance. Precisa postar mais conteúdo educativo sobre moda, não apenas editorial.",
    top_caption: "As 5 tendências que vão dominar o inverno 2026 e que vocês vão ver em TODAS as vitrines. A número 3 vocês vão pirar 👀\n\n1️⃣ Burgundy total look\n2️⃣ Couro oversized\n3️⃣ Tricô transparente (sim, é isso mesmo)\n4️⃣ Botas de cano altíssimo\n5️⃣ Maximalismo em acessórios\n\nSalva pra não esquecer na hora de montar o look! Qual é a de vocês?",
    top_likes: 48_000,
    top_comments: 5_200,
    top_views: 890_000,
    top_engagement: 2.73,
    top_score: 8.2,
    top_resumo: "Post de tendências com formato lista numerada — altíssima taxa de salvamento. 'A número 3 vocês vão pirar' cria curiosidade específica. Pergunta no final gera comentários. Formato ideal para o nicho de moda.",
    top_positivos: ["Formato lista numerada com alta taxa de salvamento", "Curiosidade específica ('a número 3')", "CTA duplo (salvar + comentar)", "Conteúdo informativo com opinião de autoridade"],
    top_negativos: ["Poderia incluir links de compra ou referências visuais", "Falta enquete nos Stories vinculada ao post"],
    top_gancho: "Excelente. '5 tendências' dá estrutura clara. 'Vão dominar' cria senso de relevância temporal. 'A número 3 vocês vão pirar' é open loop que obriga o leitor a ir até o fim.",
    top_legenda: "Lista numerada com brevidade e opinião pessoal em cada item. Linguagem acessível e entusiasmada. CTA final com pergunta aumenta comentários.",
    top_formato: "Carrossel ou Reels com 1 tendência por slide/cena seria ainda mais eficaz. Mas mesmo como post de texto, o formato lista performa muito bem para salvamentos.",
    top_hashtags: "Sem hashtags visíveis. Para o nicho de moda, #tendências2026 #modainverno #fashionbr teriam impacto positivo no alcance.",
    top_rubrica: { gancho: 5, legenda: 4, formato: 4, engajamento: 4, estrategia: 4 },
    top_recomendacoes: ["Transformar em carrossel com foto de referência de cada tendência", "Criar Stories com enquete 'Qual tendência vocês mais querem ver?'", "Fazer Reels mostrando como usar cada tendência no dia a dia"],
    worst_caption: "Café da manhã em Paris 🥐 #paris #travel",
    worst_likes: 12_000,
    worst_comments: 890,
    worst_views: 320_000,
    worst_engagement: 0.66,
    worst_score: 3.0,
    worst_resumo: "Post de lifestyle genérico sem conexão com o posicionamento de moda. 'Café da manhã em Paris' é clichê saturado de viagem. Engajamento 16% abaixo da média já baixa.",
    worst_positivos: ["Estética visual bonita e bem enquadrada"],
    worst_negativos: ["Clichê de viagem saturado sem diferencial", "Sem conexão com o posicionamento de moda/tendências", "Caption curta demais sem valor informativo", "Hashtags genéricas em inglês"],
    worst_gancho: "Zero gancho. 'Café da manhã em Paris' é genérico. Alternativa: 'O café mais instagramável de Paris custa €4 — e fica nessa rua que ninguém conhece'.",
    worst_legenda: "Cinco palavras genéricas. Cada post de uma conta com 2.4M é espaço publicitário valioso. Desperdiçar com 'Café da manhã em Paris' é jogar dinheiro fora.",
    worst_formato: "Foto estática de comida/café. Formato com menor engajamento no nicho de moda/lifestyle. Reels mostrando o café + dica de moda parisiense seria infinitamente melhor.",
    worst_hashtags: "#paris e #travel são mega-saturadas e não atraem público qualificado de moda. Zero impacto no alcance.",
    worst_rubrica: { gancho: 1, legenda: 1, formato: 2, engajamento: 1, estrategia: 1 },
    worst_recomendacoes: ["Conectar viagem com moda: 'O que as parisienses estão usando agora que vai chegar no Brasil em 3 meses'", "Criar Reels de street style em Paris com análise de tendências", "Usar caption longa com dicas práticas sobre moda francesa"],
    next_format: "Carrossel",
    next_hook: "Paris vs São Paulo: quem se veste melhor? (análise honesta)",
    next_outline: ["Slide 1: Gancho provocativo com fotos lado a lado", "Slides 2-5: Comparativo por categoria (casual, trabalho, festa, inverno)", "Slide 6: O que o Brasil faz MELHOR que Paris", "Slide 7: As tendências francesas que funcionam aqui"],
    next_cta: "Comenta 🇧🇷 ou 🇫🇷 — qual estilo vocês preferem?",
    next_angle: "Comparativo cultural com opinião de autoridade",
  },

  mohindi: {
    bio: "Cozinheiro e viajante\nHá 10 anos compartilhando receitas e viagens\nSão Paulo, BR\ncontato@mohindi.com",
    following: 2_759,
    posts_count: 3_718,
    bio_score: 6.5,
    bio_score_new: 8.5,
    suggested_bio: "Cozinheiro que viaja o mundo atrás de receitas que FUNCIONAM 🍳\n10 anos transformando ingredientes simples em pratos incríveis\n📍 SP | 🌍 +40 países\n🎥 Receita nova toda semana ↓",
    rationale: "Bio funcional mas sem impacto. 'Cozinheiro e viajante' é genérico. A sugestão diferencia com a promessa de 'receitas que funcionam' e adiciona prova social dos países visitados.",
    cta_option: "🎥 Receita nova toda semana ↓",
    criteria: { clarity: 3, authority: 3, cta: 2, seo: 3, brand_voice: 3, specificity: 3 },
    criteria_new: { clarity: 5, authority: 5, cta: 4, seo: 5, brand_voice: 4, specificity: 5 },
    proposta_valor: "'Cozinheiro e viajante' é genérico — milhares de perfis usam essa mesma descrição. Falta o diferencial: são receitas fáceis? Gourmet? De viagens? O visitante não sabe o que esperar.",
    segmentacao_publico: "Vago. 'Receitas e viagens' são dois nichos diferentes. Quem busca receitas pode não se interessar por viagens e vice-versa. Definir o foco principal ajudaria.",
    gatilhos_autoridade: "'Há 10 anos' é bom mas discreto. Faltam números: receitas publicadas, países visitados, seguidores. Longevidade precisa ser amplificada.",
    cta_conversao: "O e-mail de contato é para marcas, não para seguidores. Sem link para conteúdo, sem CTA para o público geral.",
    seo_instagram: "Tem 'receitas' e 'viagens' mas faltam variações: 'cozinha fácil', 'receitas rápidas', 'gastronomia'. São Paulo, BR ajuda na busca local.",
    tom_de_voz: "Simples e direto — funciona para gastronomia. Porém, pode parecer apático. Um toque de entusiasmo ('receitas que explodem sua mente') diferenciaria.",
    strengths: "Formato de receitas práticas com altíssima taxa de salvamento. Ganchos curiosos e ingredientes acessíveis. Produção visual apetitosa com iluminação profissional. 10 anos de consistência é prova de comprometimento.",
    improvements: "Bio não converte visitantes em seguidores. Poderia explorar mais formatos como desafios culinários e collabs com outros creators. Conteúdo de viagem deveria sempre conectar com receita para manter o nicho coeso.",
    top_caption: "Essa receita de bolo de chocolate leva 3 INGREDIENTES e fica MELHOR que de padaria. Sério. Eu testei com 5 padarias diferentes.\n\n🍫 Ingredientes:\n- 200g chocolate meio amargo\n- 4 ovos\n- 1 colher de manteiga\n\nModo de preparo no vídeo. Fica IMPOSSÍVEL de dar errado.\n\nSalva pra fazer no final de semana! 🔖",
    top_likes: 35_000,
    top_comments: 4_800,
    top_views: 1_200_000,
    top_engagement: 5.82,
    top_score: 9.0,
    top_resumo: "Receita com promessa irresistível (3 ingredientes + melhor que padaria). O gancho competitivo ('testei com 5 padarias') gera credibilidade. Lista de ingredientes na legenda facilita salvamento. 'IMPOSSÍVEL de dar errado' remove objeção principal do público.",
    top_positivos: ["Promessa específica e ousada (melhor que padaria)", "Prova social (testou com 5 padarias)", "Lista de ingredientes simples remove barreira de entrada", "CTA relevante para salvamento"],
    top_negativos: ["Poderia incluir tempo de preparo no texto", "Falta CTA para comentários"],
    top_gancho: "Excepcional. '3 ingredientes' + 'melhor que padaria' é combinação perfeita de simplicidade e superioridade. 'Testei com 5 padarias' adiciona prova concreta.",
    top_legenda: "Estrutura eficaz: promessa → prova → ingredientes → CTA. Linguagem entusiasmada mas não exagerada. O 'Sério.' como frase isolada reforça a credibilidade.",
    top_formato: "Reels de receita — formato com maior distribuição no nicho de gastronomia. Vídeo mostrando o processo é essencial para receitas.",
    top_hashtags: "Sem hashtags visíveis. Para conta de 822K, hashtags como #receitafacil #3ingredientes #bolodechocolate teriam impacto significativo.",
    top_rubrica: { gancho: 5, legenda: 5, formato: 5, engajamento: 5, estrategia: 4 },
    top_recomendacoes: ["Criar série '3 ingredientes' como marca registrada do perfil", "Adicionar 'Comenta RECEITA que eu mando a versão PDF'", "Fixar as top 3 receitas mais salvas no perfil"],
    worst_caption: "Almoço de domingo em família 🍝 #food #homemade",
    worst_likes: 5_200,
    worst_comments: 380,
    worst_views: 180_000,
    worst_engagement: 0.82,
    worst_score: 2.5,
    worst_resumo: "Post pessoal sem valor culinário. O público segue para receitas práticas, não para ver almoços em família. Engajamento 84% abaixo da média. Sem receita, sem dica, sem aprendizado.",
    worst_positivos: ["Transmite autenticidade e lado pessoal"],
    worst_negativos: ["Sem receita ou dica culinária — fora do posicionamento", "Caption genérica sem gancho", "Hashtags em inglês (#food #homemade) sem impacto no público BR", "Não aproveita o momento para ensinar algo"],
    worst_gancho: "Inexistente. 'Almoço de domingo' é rotina que não desperta curiosidade. Alternativa: 'O molho que minha vó fazia todo domingo — nunca contei essa receita pra ninguém'.",
    worst_legenda: "5 palavras genéricas. Desperdiça a oportunidade de transformar um almoço em família em conteúdo de valor.",
    worst_formato: "Foto estática de prato sem contexto. Comparado com Reels de receita que é o ponto forte da conta, esse formato não tem chance.",
    worst_hashtags: "#food e #homemade são globais e genéricas. Sem impacto no alcance brasileiro.",
    worst_rubrica: { gancho: 1, legenda: 1, formato: 2, engajamento: 1, estrategia: 1 },
    worst_recomendacoes: ["Transformar almoços em família em conteúdo: 'A receita de molho da minha avó — 3 gerações depois'", "Mesmo posts pessoais precisam de gancho culinário", "Gravar o preparo do almoço e transformar em Reels de receita"],
    next_format: "Reels",
    next_hook: "A receita de 2 ingredientes que viralizou na Itália e ninguém conhece no Brasil",
    next_outline: ["Abrir com o prato pronto (visual irresistível)", "Revelar que são só 2 ingredientes", "Mostrar o preparo passo a passo", "Provar ao vivo com reação genuína"],
    next_cta: "Comenta RECEITA que eu mando o passo a passo completo no direct 🍝",
    next_angle: "Receita internacional simplificada",
  },

  nortonmello: {
    bio: "TREINADOR - 2X World Record\nMaior live fitness no Insta do mundo\nTransformo seu corpo com treinos em casa\nCLICA NO LINK e BAIXE MEU APP 👇",
    following: 1_582,
    posts_count: 2_174,
    bio_score: 7.8,
    bio_score_new: 9.0,
    suggested_bio: "Treinador | 2x Recorde Mundial de Fitness 🏆\nMaior live fitness do Instagram no mundo\n+500K transformações com treinos em casa\n📱 Baixe o app e comece HOJE ↓",
    rationale: "Bio já é forte com 2 recordes mundiais e 'maior live'. Pode melhorar adicionando número de transformações como prova social e CTA mais urgente.",
    cta_option: "📱 Baixe o app e comece HOJE ↓",
    criteria: { clarity: 4, authority: 5, cta: 4, seo: 3, brand_voice: 4, specificity: 4 },
    criteria_new: { clarity: 5, authority: 5, cta: 5, seo: 4, brand_voice: 5, specificity: 5 },
    proposta_valor: "Clara e diferenciada: 'transformo seu corpo com treinos em casa'. O visitante sabe exatamente o que vai receber. Direto ao ponto.",
    segmentacao_publico: "'Treinos em casa' segmenta bem — atrai quem não quer ir à academia. Público definido e acessível.",
    gatilhos_autoridade: "Excelentes: 2x World Record e 'maior live fitness no Insta do mundo'. Difícil competir com esses gatilhos. São provas concretas e verificáveis.",
    cta_conversao: "'CLICA NO LINK e BAIXE MEU APP' é direto e claro. Caps lock pode parecer agressivo — 'Baixe o app e comece hoje ↓' seria mais elegante.",
    seo_instagram: "'Fitness' e 'treinos em casa' são bons keywords. Faltam variações como 'personal trainer', 'emagrecer', 'treino funcional'.",
    tom_de_voz: "Energético e motivacional — combina perfeitamente com o nicho fitness. O tom caps lock reforça energia mas pode parecer apelativo.",
    strengths: "Prova social com transformações reais e recordes mundiais. Conteúdo acessível com treinos em casa (sem equipamento). Formato de lives cria comunidade e engajamento em tempo real.",
    improvements: "Hashtags genéricas (#fitness #gym) não atraem público qualificado. Formato carrossel educativo sobre exercícios específicos pode aumentar salvamentos. Precisa de mais conteúdo educativo (nutrição, periodização) além de treinos.",
    top_caption: "Meu aluno perdeu 22kg em 6 meses fazendo ISSO. Não é dieta maluca, não é remédio, é CIÊNCIA.\n\nTreino de 20 minutos em casa, 5x por semana. Sem equipamento. Sem desculpa.\n\nVou te mostrar exatamente o treino que ele fez. Desliza 👉\n\nAntes: 98kg | Depois: 76kg\nAntes: cansava subindo escada | Depois: corre 5km\n\nSe ele conseguiu, você também consegue. Comenta EU QUERO que eu mando o treino completo 💪",
    top_likes: 42_000,
    top_comments: 8_900,
    top_views: 1_800_000,
    top_engagement: 6.65,
    top_score: 8.9,
    top_resumo: "Transformação real com números concretos que geram identificação. Estrutura: prova social → simplicidade do método → CTA para comentário. 'Sem equipamento, sem desculpa' remove objeções. O 'EU QUERO' como CTA gera alto volume de comentários que amplifica o alcance.",
    top_positivos: ["Transformação real com números antes/depois verificáveis", "Remove objeções (sem equipamento, sem academia)", "CTA 'EU QUERO' gera tsunami de comentários", "Estrutura que prova acessibilidade do método"],
    top_negativos: ["Poderia incluir idade do aluno para mais identificação", "Falta menção ao app como próximo passo"],
    top_gancho: "'22kg em 6 meses' é gancho numérico poderoso. 'Fazendo ISSO' cria curiosidade sobre o método. 'Não é dieta maluca' remove ceticismo antes dele surgir.",
    top_legenda: "Narrativa de transformação perfeita: problema → método simples → resultado → CTA. O contraste antes/depois (escada vs 5km) é mais impactante que só o peso.",
    top_formato: "Carrossel com antes/depois + exercícios. Formato ideal para transformações porque permite contar a história visual em etapas.",
    top_hashtags: "Hashtags como #transformação #treinoemcasa #emagrecimento teriam bom impacto. Evitar genéricos como #fitness.",
    top_rubrica: { gancho: 5, legenda: 5, formato: 5, engajamento: 5, estrategia: 4 },
    top_recomendacoes: ["Criar série semanal de transformações reais de alunos", "Vincular com Stories mostrando trechos do treino e direcionando ao app", "Fazer collab com o aluno transformado para dar depoimento ao vivo"],
    worst_caption: "Dia de perna 🦵 #legday #gym #fitness",
    worst_likes: 6_800,
    worst_comments: 520,
    worst_views: 280_000,
    worst_engagement: 1.02,
    worst_score: 2.4,
    worst_resumo: "Post genérico de academia que poderia ser de qualquer personal. 'Dia de perna' é clichê fitness sem nenhum valor educativo ou motivacional. Engajamento 51% abaixo da média.",
    worst_positivos: ["Mostra rotina pessoal de treino (autenticidade)"],
    worst_negativos: ["Clichê fitness saturado sem diferencial", "Sem valor educativo (qual exercício? quantas séries?)", "Hashtags genéricas em inglês (#legday)", "Desconectado do posicionamento 'treinos em casa'"],
    worst_gancho: "Zero. 'Dia de perna' é o clichê mais usado no fitness. Alternativa: 'O exercício de perna que substituiu o agachamento no meu treino — e o resultado em 30 dias'.",
    worst_legenda: "4 palavras. Para um treinador com 2 recordes mundiais, isso é desperdício total. Cada post poderia educar centenas de milhares de pessoas.",
    worst_formato: "Foto estática na academia — contraditório com o posicionamento 'treinos em casa'. Cria confusão na audiência.",
    worst_hashtags: "#legday, #gym, #fitness — todas em inglês, todas genéricas, zero impacto no público brasileiro.",
    worst_rubrica: { gancho: 1, legenda: 1, formato: 1, engajamento: 1, estrategia: 1 },
    worst_recomendacoes: ["Nunca postar 'dia de X' sem contexto educativo — sempre adicionar exercício + técnica + dica", "Manter consistência com posicionamento 'treinos em casa'", "Transformar treinos de perna em Reels tutorial com série de exercícios"],
    next_format: "Reels",
    next_hook: "O treino de perna de 10 minutos que substitui 1 hora de academia",
    next_outline: ["Mostrar o timer: 10 minutos no relógio", "4 exercícios de 2 minutos cada + 2 min descanso", "Demonstrar cada exercício com forma correta", "Mostrar músculos ativados (overlay gráfico simples)"],
    next_cta: "Salva esse treino e faz amanhã de manhã — depois me conta o resultado 💪",
    next_angle: "Treino em casa eficiente e rápido",
  },

  whinderssonnunes: {
    bio: "ISSO DEFINITIVAMENTE NAO E UM CULTO",
    following: 2_766,
    posts_count: 792,
    bio_score: 3.5,
    bio_score_new: 7.5,
    suggested_bio: "O maior comediante digital do Brasil 🇧🇷\n🎤 Turnê 2026 — ingressos esgotando\n😂 Humor com verdade\n🎬 +40M no YouTube ↓",
    rationale: "Bio é uma piada interna que funciona para quem já conhece, mas não converte visitantes novos. Não diz quem é, o que faz ou por que seguir. A sugestão mantém o humor mas adiciona posicionamento e CTA.",
    cta_option: "🎬 +40M no YouTube ↓",
    criteria: { clarity: 1, authority: 1, cta: 1, seo: 1, brand_voice: 5, specificity: 1 },
    criteria_new: { clarity: 4, authority: 5, cta: 4, seo: 3, brand_voice: 5, specificity: 4 },
    proposta_valor: "Inexistente para quem não conhece. 'ISSO DEFINITIVAMENTE NÃO É UM CULTO' é humor puro sem informação. Funciona para fãs existentes mas não converte novos seguidores.",
    segmentacao_publico: "Zero segmentação. Sem indicação de nicho (humor, música, reflexões). Visitante novo precisa explorar o feed para entender o que o perfil oferece.",
    gatilhos_autoridade: "Nenhum visível. Não menciona 56M de seguidores, 40M no YouTube, turnês esgotadas, ou participações em TV. Todo esse capital de autoridade está desperdiçado.",
    cta_conversao: "Sem CTA. Nenhum link, nenhum direcionamento. Para uma turnê ativa, isso é perder vendas de ingressos diariamente.",
    seo_instagram: "Zero SEO. Palavras como 'comediante', 'humor', 'stand-up' não aparecem. Impossível ser encontrado via busca do Instagram.",
    tom_de_voz: "100% autêntico e engraçado — é o Whindersson puro. Mas sacrifica toda a funcionalidade por uma piada. Com 56M de seguidores ele pode se dar esse luxo, mas ainda assim perde conversões.",
    strengths: "Alcance massivo e orgânico (56.5M). Storytelling natural e genuíno. Capacidade de viralizar qualquer formato. Audiência extremamente engajada (3.52% em conta gigante é excepcional). Versatilidade entre humor, música e conteúdo pessoal.",
    improvements: "Bio não converte visitantes novos em seguidores. Posts sem narrativa (fotos aleatórias) performam muito abaixo da média. Turnê poderia ser promovida com mais estratégia na bio e nos posts.",
    top_caption: "POV: você descobriu que seu amigo não tempera o frango 😭\n\nIsso é real e eu preciso contar pra vocês. Fui na casa do meu amigo, ele fez frango grelhado. Até aí tudo bem. Aí eu perguntei: 'que tempero tu usou?' Ele olhou pra mim com a maior naturalidade do mundo e falou: 'sal.'\n\nSAL. SÓ SAL.\n\nEu olhei pro frango. Olhei pra ele. Olhei pro frango de novo. E entendi que nossa amizade nunca mais seria a mesma.\n\nMarca aquele amigo que não sabe temperar NADA 😂👇",
    top_likes: 2_800_000,
    top_comments: 185_000,
    top_views: 42_000_000,
    top_engagement: 5.28,
    top_score: 9.3,
    top_resumo: "Storytelling humorístico perfeito com situação cotidiana universalmente identificável. O POV + história real cria conexão imediata. Escalonamento da reação (olhou pro frango, olhou pra ele, olhou pro frango de novo) é técnica de comédia clássica. CTA de marcação gera volume massivo de comentários.",
    top_positivos: ["Situação cotidiana que TODOS se identificam", "Storytelling com escalonamento cômico perfeito", "CTA de marcação gera avalanche de comentários", "Linguagem conversacional autêntica e natural"],
    top_negativos: ["Poderia ter follow-up nos Stories com a reação do amigo", "Falta CTA para salvamento além da marcação"],
    top_gancho: "POV + situação absurda = combinação irresistível. 'Descobriu que seu amigo não tempera o frango' é específico o suficiente para ser engraçado e genérico o suficiente para ser identificável.",
    top_legenda: "Narrativa cômica com timing perfeito. Frases curtas criam ritmo de stand-up. O 'SAL. SÓ SAL.' em caps funciona como punchline visual. A conclusão ('nossa amizade nunca mais seria a mesma') fecha com humor seco.",
    top_formato: "Reels com narração + atuação. Formato que maximiza o talento de Whindersson. Combinação de texto escrito + performance visual é imbatível para humor.",
    top_hashtags: "Sem hashtags — desnecessárias para conta de 56M. O engajamento orgânico já garante distribuição massiva.",
    top_rubrica: { gancho: 5, legenda: 5, formato: 5, engajamento: 5, estrategia: 5 },
    top_recomendacoes: ["Criar série 'POV: seu amigo...' como formato recorrente", "Fazer dueto/collab com o amigo para follow-up (meta humor)", "Usar a mesma estrutura de storytelling + situação cotidiana para outros temas"],
    worst_caption: "Vibes ✌️ #mood",
    worst_likes: 320_000,
    worst_comments: 12_000,
    worst_views: 5_200_000,
    worst_engagement: 0.59,
    worst_score: 2.0,
    worst_resumo: "Post vazio que desperdiça o talento narrativo do Whindersson. 'Vibes' não é gancho, não conta história, não gera interação qualificada. Engajamento 83% abaixo da média. Para 56M de seguidores, isso é desperdiçar alcance de um programa de TV.",
    worst_positivos: ["Mantém presença no feed (alguma coisa é melhor que nada)"],
    worst_negativos: ["Zero storytelling — justamente o ponto forte do perfil", "Uma palavra como caption é desperdício total", "Hashtag #mood não comunica nada", "Sem CTA, sem engajamento, sem propósito"],
    worst_gancho: "Inexistente. 'Vibes' é literalmente anti-conteúdo. O scroll continua sem hesitar. O algoritmo interpreta como conteúdo de baixo valor.",
    worst_legenda: "Uma palavra. Para o maior comediante digital do Brasil, isso é como um chef servir um prato vazio.",
    worst_formato: "Foto estática sem contexto. Para um creator de humor/performance, formato com menor potencial possível.",
    worst_hashtags: "#mood — hashtag genérica com bilhões de posts. Zero impacto.",
    worst_rubrica: { gancho: 1, legenda: 1, formato: 1, engajamento: 1, estrategia: 1 },
    worst_recomendacoes: ["Mesmo fotos casuais precisam de micro-storytelling: 'Essa foto foi tirada 5 minutos antes de eu descobrir que...'", "Nunca postar sem narrativa — o algoritmo e o público esperam história", "Usar posts pessoais como setup para humor: o cenário da foto vira contexto para uma piada"],
    next_format: "Reels",
    next_hook: "POV: você vai jantar na casa do amigo que não sabe cozinhar... de novo",
    next_outline: ["Chegada na casa com expectativa zero", "O amigo apresentando o 'jantar especial' (miojo com ovo)", "Reação de desespero contido", "Plot twist: na verdade ficou bom (ou não)"],
    next_cta: "Marca o amigo que cozinha PIOR que isso 😂",
    next_angle: "Humor cotidiano com storytelling",
  },

  manualdomundo: {
    bio: "Desbravadores do conhecimento\nContato: contato@manualdomundo.com.br\nSiga @amarifulfaro",
    following: 57,
    posts_count: 5_964,
    bio_score: 5.5,
    bio_score_new: 8.5,
    suggested_bio: "Transformando ciência em diversão desde 2008 🧪\n📺 +18M no YouTube | A maior família de ciência do Brasil\n🔬 Experimentos incríveis toda semana\n🎥 Novo vídeo ↓",
    rationale: "Bio vaga — 'desbravadores do conhecimento' é bonito mas não comunica o que o perfil faz. Não menciona YouTube (18M), longevidade (desde 2008) nem o tipo de conteúdo. A sugestão destaca autoridade e consistência.",
    cta_option: "🎥 Novo vídeo ↓",
    criteria: { clarity: 2, authority: 2, cta: 1, seo: 2, brand_voice: 3, specificity: 2 },
    criteria_new: { clarity: 5, authority: 5, cta: 4, seo: 4, brand_voice: 5, specificity: 5 },
    proposta_valor: "'Desbravadores do conhecimento' é vago e poderia descrever uma editora, escola ou canal de história. Não diz que fazem experimentos, ciência pop ou conteúdo educativo visual.",
    segmentacao_publico: "Sem segmentação. O público (pais, professores, curiosos, crianças) não se identifica. 'Se você é curioso sobre como o mundo funciona' seria mais eficaz.",
    gatilhos_autoridade: "Nenhum. Não menciona 18M no YouTube, 16 anos de existência, prêmios, ou escala do canal. Todo esse capital de credibilidade é invisível na bio.",
    cta_conversao: "Sem CTA para conteúdo. O 'Siga @amarifulfaro' direciona para outra conta em vez de converter para o próprio conteúdo.",
    seo_instagram: "Zero keywords de busca. 'Ciência', 'experimentos', 'educação', 'curiosidades' — nenhum desses termos aparece. Impossível ser descoberto via search.",
    tom_de_voz: "Institucional demais. 'Desbravadores do conhecimento' soa como slogan corporativo. O conteúdo é divertido e acessível — a bio deveria refletir isso.",
    strengths: "Conteúdo educativo com altíssimo valor de entretenimento. Formato único que mistura ciência com espetáculo visual. Autoridade construída em 16 anos de consistência. Público familiar que confia e recomenda.",
    improvements: "Instagram é secundário vs YouTube — não aproveita o potencial da plataforma. Reels adaptados dos vídeos longos com ganchos mais curtos poderiam dobrar o engajamento. Bio não converte visitantes em seguidores.",
    top_caption: "O que acontece quando você joga 10 QUILOS de gelo seco numa piscina? 🌊\n\nO resultado é INSANO. A piscina inteira virou uma nuvem de fumaça em 3 segundos.\n\nMas a física por trás é ainda mais incrível: o gelo seco (-78°C) sublima direto de sólido para gás quando toca a água a 28°C. São 106 graus de diferença de temperatura!\n\nO volume de CO₂ gerado é 800x maior que o gelo sólido original. Por isso a explosão de névoa.\n\n⚠️ NÃO façam isso em casa — CO₂ em ambiente fechado é perigoso.\n\nSalva pra mostrar pra alguém que não acredita! 🔬",
    top_likes: 89_000,
    top_comments: 6_200,
    top_views: 3_500_000,
    top_engagement: 3.80,
    top_score: 8.7,
    top_resumo: "Combinação perfeita de espetáculo visual + educação científica. O gancho '10 QUILOS de gelo seco' é dimensional e ativa imaginação. A explicação científica agrega valor real. O aviso de segurança reforça responsabilidade e autoridade.",
    top_positivos: ["Gancho dimensional que ativa imaginação (10 quilos, piscina inteira)", "Educação científica acessível integrada ao entretenimento", "Aviso de segurança reforça autoridade e responsabilidade", "Visual espetacular que incentiva compartilhamento"],
    top_negativos: ["Poderia ter pergunta para gerar comentários", "Falta sequência de Stories com bastidores do experimento"],
    top_gancho: "Excepcional. '10 QUILOS de gelo seco numa piscina' — escala exagerada cria curiosidade. A pergunta retórica 'O que acontece?' é irresistível.",
    top_legenda: "Estrutura: espetáculo → ciência → segurança → CTA. Equilíbrio perfeito entre entretenimento e educação. Números específicos (-78°C, 800x, 106 graus) dão credibilidade sem complicar.",
    top_formato: "Reels de experimento — formato ideal para Manual do Mundo. O visual espetacular garante retenção nos primeiros 3 segundos.",
    top_hashtags: "Hashtags como #ciência #experimento #física #manualdomundo teriam bom impacto para alcance educativo.",
    top_rubrica: { gancho: 5, legenda: 5, formato: 5, engajamento: 4, estrategia: 4 },
    top_recomendacoes: ["Criar série de 'O que acontece quando...' como formato recorrente no Instagram", "Adicionar pergunta: 'Qual próximo experimento vocês querem ver?'", "Fazer versão curta (15s) para Reels e versão longa para YouTube"],
    worst_caption: "Bastidores do estúdio 🎬 #behindthescenes",
    worst_likes: 8_500,
    worst_comments: 420,
    worst_views: 310_000,
    worst_engagement: 0.37,
    worst_score: 2.6,
    worst_resumo: "Post de bastidores sem contexto científico ou educativo. O público segue para experimentos e ciência, não para ver estúdio. Caption genérica de 4 palavras. Engajamento 54% abaixo da média.",
    worst_positivos: ["Humaniza a equipe e mostra o trabalho por trás"],
    worst_negativos: ["Sem contexto científico ou educativo", "Caption genérica sem gancho", "Hashtag em inglês desconectada do público", "Não conecta bastidores com o próximo experimento"],
    worst_gancho: "Inexistente. 'Bastidores do estúdio' é genérico. Alternativa: 'Esse é o equipamento que quase explodiu ontem durante a gravação do próximo vídeo 👀'.",
    worst_legenda: "4 palavras. Bastidores poderiam ser fascinantes se contextualizados: qual experimento está sendo preparado? O que deu errado? O que vem por aí?",
    worst_formato: "Foto estática de estúdio. Tour em Reels mostrando os equipamentos + teaser do próximo experimento seria infinitamente mais engajante.",
    worst_hashtags: "#behindthescenes em inglês, público brasileiro. Sem impacto.",
    worst_rubrica: { gancho: 1, legenda: 1, formato: 2, engajamento: 1, estrategia: 1 },
    worst_recomendacoes: ["Bastidores devem sempre ter teaser: 'Preparando o experimento mais perigoso que já fizemos — sai sexta'", "Mostrar equipamento sendo montado + o que pode dar errado cria antecipação", "Usar bastidores como lead-in para o vídeo completo no YouTube"],
    next_format: "Reels",
    next_hook: "O que acontece quando você mistura Coca-Cola com leite (o resultado é nojento e incrível ao mesmo tempo)",
    next_outline: ["Mostrar os ingredientes (setup simples)", "Misturar ao vivo com reação de suspense", "Esperar 6 horas (time-lapse)", "Revelar a separação (caseína coagulada) e explicar a química"],
    next_cta: "Comenta qual mistura maluca vocês querem que a gente teste 🧪",
    next_angle: "Experimento caseiro com ciência acessível",
  },

  eduardofeldberg: {
    bio: "Finanças e humor pra quem enjoou de ser pobre\nApresentador @pobreshow\nFundador @vencerincorporadora\nSócio @livar.br",
    following: 474,
    posts_count: 4_765,
    bio_score: 7.8,
    bio_score_new: 9.0,
    suggested_bio: "Finanças sem cara de banco 😂💰\nVocê vai rir, aprender e investir — nessa ordem\n🎬 Apresentador @pobreshow | Fundador @vencerincorporadora\n📊 Curso gratuito ↓",
    rationale: "Bio boa mas pode ser mais memorável. 'Pra quem enjoou de ser pobre' é forte mas um pouco agressivo. A sugestão mantém o humor como diferencial e adiciona sequência (rir → aprender → investir).",
    cta_option: "📊 Curso gratuito ↓",
    criteria: { clarity: 4, authority: 4, cta: 2, seo: 3, brand_voice: 5, specificity: 4 },
    criteria_new: { clarity: 5, authority: 5, cta: 5, seo: 4, brand_voice: 5, specificity: 5 },
    proposta_valor: "'Finanças e humor pra quem enjoou de ser pobre' é proposta de valor excelente — diferencia de todos os outros perfis de finanças. Quem lê sabe exatamente o que vai receber.",
    segmentacao_publico: "'Quem enjoou de ser pobre' — segmentação perfeita. Fala com iniciantes que acham finanças chato. Não tenta agradar investidores avançados.",
    gatilhos_autoridade: "Menciona @pobreshow, @vencerincorporadora e @livar.br — bons mas podem confundir sem contexto. Faltam números (seguidores, alunos formados, patrimônio gerido).",
    cta_conversao: "Sem CTA. Quatro linhas de bio e nenhuma direciona o visitante a uma ação. O link na bio perde potencial sem um convite claro.",
    seo_instagram: "'Finanças' e 'humor' são keywords bons. Faltam variações como 'investimentos', 'como investir', 'educação financeira' para SEO.",
    tom_de_voz: "Perfeito. O humor na bio prepara o visitante para o tom do conteúdo. 'Enjoou de ser pobre' é provocativo e memorável — diferencia de perfis de finanças sérios.",
    strengths: "Combinação única de humor + educação financeira que ninguém mais faz nessa escala. Ganchos com celebridades e situações do cotidiano. Linguagem acessível que atrai público que não se identifica com finanças 'tradicionais'.",
    improvements: "Posts genéricos de 'bom dia mercado' sem humor performam mal. O diferencial é o humor — TODOS os posts precisam desse elemento. Bio sem CTA perde conversões para o curso e produtos.",
    top_caption: "Se o Neymar investisse os R$87 milhões que ele gasta POR MÊS em renda fixa, em 1 ano ele teria...\n\n*pega a calculadora*\n\nR$87M × 12 meses = R$1,044 BILHÃO investido\nA 13% ao ano (Selic) = R$135 MILHÕES só de juros\n\nOu seja: o Neymar ganharia R$11,3 MILHÕES POR MÊS SEM FAZER NADA.\n\nMas não. O cara compra o 47º carro.\n\nA gente ri (e chora) mas a lição serve pra todo mundo: juros compostos são o 8º milagre do mundo. Seu dinheiro PODE trabalhar pra você.\n\nComenta quanto você investe por mês (sem julgamento, a gente tá aqui pra crescer junto) 💰",
    top_likes: 125_000,
    top_comments: 14_200,
    top_views: 4_500_000,
    top_engagement: 4.35,
    top_score: 9.2,
    top_resumo: "Formato 'gancho com celebridade + cálculo real + lição prática' é a assinatura do Feldberg. Neymar gera curiosidade universal, os números concretos dão credibilidade, e a punchline ('compra o 47º carro') adiciona humor. O CTA no final cria comunidade.",
    top_positivos: ["Gancho com celebridade que gera curiosidade universal", "Cálculos reais que educam enquanto entretêm", "Punchline humorística que diferencia de perfis de finanças sérios", "CTA que cria comunidade ('sem julgamento')"],
    top_negativos: ["Poderia incluir link para simulador ou ferramenta", "Falta versão em carrossel para quem prefere formato visual"],
    top_gancho: "'R$87 milhões POR MÊS' — número absurdo que para o scroll. Neymar como personagem universal. 'Se investisse em renda fixa...' cria curiosidade sobre o resultado.",
    top_legenda: "Narrativa cômica com educação financeira embutida. O cálculo é real e verificável. A punchline transforma a lição em entretenimento. Formato assinatura que o público reconhece.",
    top_formato: "Reels com narração + overlay de números na tela. Formato ideal para combinar humor + dados. O ritmo da narração segura a atenção.",
    top_hashtags: "Para conta de 3.2M, hashtags como #finanças #investimentos #educaçãofinanceira teriam impacto moderado.",
    top_rubrica: { gancho: 5, legenda: 5, formato: 5, engajamento: 5, estrategia: 5 },
    top_recomendacoes: ["Criar série 'Se [celebridade] investisse...' — formato replicável infinitamente", "Adicionar 'Manda pro amigo que gasta tudo no ifood' como segundo CTA", "Fazer versão carrossel com os cálculos para maximizar salvamentos"],
    worst_caption: "Bom dia, mercado! 📈 #bolsadevalores #investimentos",
    worst_likes: 8_500,
    worst_comments: 620,
    worst_views: 380_000,
    worst_engagement: 0.35,
    worst_score: 2.2,
    worst_resumo: "Post genérico que poderia ser de qualquer perfil de finanças. 'Bom dia mercado' é clichê do nicho financeiro. Zero humor — justamente o diferencial do Feldberg. Engajamento 77% abaixo da média.",
    worst_positivos: ["Mantém consistência de postagem diária"],
    worst_negativos: ["Zero humor — elimina o diferencial competitivo do perfil", "Clichê do nicho financeiro ('bom dia mercado')", "Sem valor educativo ou de entretenimento", "Hashtags genéricas sem impacto"],
    worst_gancho: "Inexistente. 'Bom dia mercado' é ruído de fundo — todo perfil de finanças posta isso. Alternativa: 'O mercado abriu caindo 3% e seu cunhado já tá vendendo tudo. Calma. Deixa eu explicar.'",
    worst_legenda: "4 palavras sem personalidade. O Eduardo Feldberg que faz humor com Neymar e faz conta ao vivo tem o MESMO perfil que posta 'Bom dia mercado'. Incoerência de brand voice.",
    worst_formato: "Post estático de texto/imagem genérica. Sem performance, sem humor, sem dados. Formato que qualquer estagiário de corretora postaria.",
    worst_hashtags: "#bolsadevalores e #investimentos são saturadas e não diferenciam o perfil dos milhares de outros perfis de finanças.",
    worst_rubrica: { gancho: 1, legenda: 1, formato: 1, engajamento: 1, estrategia: 1 },
    worst_recomendacoes: ["Nunca postar conteúdo genérico de finanças — o diferencial é SEMPRE humor", "Substituir 'bom dia mercado' por: 'O mercado caiu 2% e minha mãe já ligou perguntando se eu perdi tudo'", "Cada post deve ter a assinatura Feldberg: celebridade + cálculo + punchline"],
    next_format: "Reels",
    next_hook: "Se a Virgínia Fonseca investisse 1% do que ela ganha com publi...",
    next_outline: ["Revelar quanto influencers do porte da Virginia ganham com publi (~R$500K/post)", "Calcular 1% investido por mês em renda fixa", "Mostrar o montante acumulado em 5 anos", "Punchline: 'Mas ela prefere comprar a 15ª mansão'"],
    next_cta: "Comenta 1% se você investe pelo menos 1% do que ganha 💰",
    next_angle: "Humor com celebridade + cálculo real",
  },

  virginia: {
    bio: "2026 é NOSSO\nToda honra e glória a Deus\nCONTATO: publi@virginiafonseca.com",
    following: 706,
    posts_count: 3_100,
    bio_score: 4.5,
    bio_score_new: 8.0,
    suggested_bio: "Mãe, empresária e a maior influenciadora do Brasil 🇧🇷\n💄 Fundadora @wepinkoficial\n👨‍👩‍👧‍👦 Maria Alice, Maria Flor e Zé Leonardo\n✨ Novidades ↓",
    rationale: "Bio não comunica quem é Virginia para quem não conhece. '2026 é NOSSO' é genérico. Não menciona WePink (empresa bilionária), filhos (maior conexão com público) ou escala do perfil. A sugestão posiciona corretamente.",
    cta_option: "✨ Novidades ↓",
    criteria: { clarity: 1, authority: 1, cta: 1, seo: 1, brand_voice: 3, specificity: 1 },
    criteria_new: { clarity: 5, authority: 5, cta: 4, seo: 3, brand_voice: 4, specificity: 5 },
    proposta_valor: "Inexistente. '2026 é NOSSO' não diz nada sobre quem é Virginia. 'Toda honra e glória a Deus' é pessoal mas não posiciona. O contato de publi é para marcas, não seguidores.",
    segmentacao_publico: "Zero segmentação. Não indica lifestyle, maternidade, beleza ou empreendedorismo. Para 54M de seguidores, a bio deveria indicar claramente o tipo de conteúdo.",
    gatilhos_autoridade: "Nenhum. Não menciona WePink (empresa bilionária), 54M de seguidores, ou posição como maior influenciadora do Brasil. Capital de autoridade completamente desperdiçado.",
    cta_conversao: "Sem CTA para seguidores. O e-mail de publi funciona para marcas mas o público geral não tem nenhum direcionamento.",
    seo_instagram: "Zero keywords. 'Influenciadora', 'mãe', 'lifestyle', 'WePink' — nenhum aparece. Não é encontrável via busca.",
    tom_de_voz: "Motivacional e religioso — reflete valores pessoais. Mas sem contexto de quem ela é, soa genérico para novos visitantes.",
    strengths: "Conexão emocional fortíssima com público através de conteúdo familiar autêntico. Volume de conteúdo diário mantém audiência ativa. Engajamento de 3.5% é excepcional para 54M. WePink como empresa fortalece posicionamento de empreendedora.",
    improvements: "Bio não converte novos visitantes em seguidores. Posts sem contexto emocional ou familiar performam muito abaixo da média. O público quer Virginia mãe e empresária, não conteúdo genérico.",
    top_caption: "A Maria Alice aprendeu a falar 'mamãe' e eu CHOREI no meio do shopping 😭💛\n\nGente, não tava preparada. A gente tava andando e do nada ela olhou pra mim e falou 'mamãe' com aquela vozinha.\n\nEu larguei tudo no chão. Bolsa, sacola, celular. Tudo. Sentei no chão do shopping e chorei.\n\nAs pessoas passando acharam que eu tava maluca. E eu tava mesmo. Maluca de amor.\n\nIsso não tem preço. Não tem publi que pague. Não tem carro, casa ou bolsa que chegue perto desse momento.\n\nMamães, vocês lembram do primeiro 'mamãe'? Me conta 💛👇",
    top_likes: 3_200_000,
    top_comments: 245_000,
    top_views: 38_000_000,
    top_engagement: 6.38,
    top_score: 9.4,
    top_resumo: "Momento maternal autêntico que gera identificação universal entre mães. A narrativa detalhada (largou tudo no chão, sentou no shopping) torna o momento vivido e real. 'Maluca de amor' é frase que resume a maternidade. CTA para mães compartilharem suas experiências gera volume massivo de comentários.",
    top_positivos: ["Momento autêntico que gera identificação universal entre mães", "Narrativa detalhada que torna o momento vivido e real", "Frase 'maluca de amor' é compartilhável e memorável", "CTA que convida outras mães a compartilhar gera comunidade"],
    top_negativos: ["Poderia vincular com Stories mostrando o vídeo do momento", "Falta CTA para salvamento além dos comentários"],
    top_gancho: "'Maria Alice aprendeu a falar mamãe' — gancho emocional irresistível para mães. 'CHOREI no meio do shopping' adiciona drama e cenário que torna visual.",
    top_legenda: "Storytelling emocional perfeito com detalhes sensoriais (vozinha, sentou no chão, pessoas passando). A escalada emocional culmina em 'maluca de amor'. Autenticidade pura.",
    top_formato: "Post com foto/vídeo do momento. Para conteúdo maternal, a autenticidade do momento é mais importante que produção. O formato cru funciona melhor.",
    top_hashtags: "Desnecessárias para 54M. O engajamento orgânico garante distribuição massiva.",
    top_rubrica: { gancho: 5, legenda: 5, formato: 5, engajamento: 5, estrategia: 5 },
    top_recomendacoes: ["Documentar mais 'primeiras vezes' dos filhos — audiência vive para esses momentos", "Criar série 'Diário de mãe' com momentos reais e sem produção", "Vincular momentos emocionais com Stories ao longo do dia para manter engajamento"],
    worst_caption: "Boa noite 🌙 #goodnight",
    worst_likes: 380_000,
    worst_comments: 15_000,
    worst_views: 4_800_000,
    worst_engagement: 0.73,
    worst_score: 2.1,
    worst_resumo: "Post vazio que desperdiça o potencial de alcance de 54M de seguidores. 'Boa noite' é o post mais genérico possível. Sem história, sem emoção, sem contexto familiar. Engajamento 79% abaixo da média. A hashtag em inglês não faz sentido para o público brasileiro.",
    worst_positivos: ["Mantém presença diária no feed"],
    worst_negativos: ["Zero storytelling ou conteúdo emocional", "Duas palavras desperdiçam alcance de milhões", "Hashtag em inglês desconectada do público", "Não se conecta com nenhum pilar (mãe, empresária, lifestyle)"],
    worst_gancho: "Inexistente. 'Boa noite' é ruído que o algoritmo ignora. Alternativa: 'Boa noite de quem acabou de colocar 3 crianças pra dormir sozinha e sobreviveu 😂💛'.",
    worst_legenda: "Duas palavras. Para a maior influenciadora do Brasil, cada post alcança mais pessoas que muitos programas de TV. Desperdiçar com 'Boa noite' é subaproveitamento extremo.",
    worst_formato: "Foto/selfie estática sem contexto. O formato que menos performa no Instagram atual.",
    worst_hashtags: "#goodnight em inglês para público brasileiro. Sem qualquer propósito estratégico.",
    worst_rubrica: { gancho: 1, legenda: 1, formato: 1, engajamento: 1, estrategia: 1 },
    worst_recomendacoes: ["Mesmo 'boa noite' pode ser conteúdo: 'Acabei de colocar os 3 pra dormir. O Zé Leonardo não queria de jeito nenhum. Tática que funcionou: [dica]'", "Nunca postar sem contexto maternal/familiar — é o que o público espera e ama", "Usar o momento noturno para reflexão rápida sobre maternidade/empreendedorismo"],
    next_format: "Reels",
    next_hook: "Um dia inteiro como mãe de 3 (versão REAL, sem filtro)",
    next_outline: ["6h: acordar com o Zé Leonardo chorando", "8h: café da manhã caótico tentando alimentar 3 crianças", "12h: reunião da WePink com criança no colo", "20h: rotina de sono que (às vezes) funciona"],
    next_cta: "Mamãe de quantos? Comenta a quantidade de filhos e como você sobrevive 😂💛",
    next_angle: "Day in the life maternal autêntico",
  },
};

function buildShowcaseResult(profile: ShowcaseProfile): AnalysisResult {
  const d = PROFILES[profile.handle];
  if (!d) return buildFallbackResult(profile);

  return {
    profile: {
      handle: profile.handle,
      full_name: profile.name,
      avatar_url: profile.avatar_url,
      bio_text: d.bio,
      followers: profile.followers,
      following: d.following,
      posts_count: d.posts_count,
      is_verified: profile.is_verified,
    },
    deliverables: {
      bio_suggestion: {
        current_bio: d.bio,
        suggested_bio: d.suggested_bio,
        rationale_short: d.rationale,
        cta_option: d.cta_option,
        score: d.bio_score,
        score_new: d.bio_score_new,
        criteria: d.criteria,
        criteria_new: d.criteria_new,
        diagnostic: {
          proposta_valor: d.proposta_valor,
          segmentacao_publico: d.segmentacao_publico,
          gatilhos_autoridade: d.gatilhos_autoridade,
          cta_conversao: d.cta_conversao,
          seo_instagram: d.seo_instagram,
          tom_de_voz: d.tom_de_voz,
        },
        strengths: d.strengths,
        improvements: d.improvements,
      },
      top_post: {
        post_id: `${profile.handle}_top`,
        permalink: `https://instagram.com/${profile.handle}`,
        thumb_url: `https://picsum.photos/seed/${profile.handle}top/400/400`,
        caption_preview: d.top_caption,
        metrics: {
          likes: d.top_likes,
          comments: d.top_comments,
          views: d.top_views,
          engagement_score: d.top_engagement / 100,
        },
        tier: "gold" as const,
        analysis: {
          resumo_desempenho: d.top_resumo,
          fatores_positivos: d.top_positivos,
          fatores_negativos: d.top_negativos,
          analise_gancho: d.top_gancho,
          analise_legenda: d.top_legenda,
          analise_formato: d.top_formato,
          analise_hashtags: d.top_hashtags,
          rubrica: d.top_rubrica,
          nota_geral: d.top_score,
          recomendacoes: d.top_recomendacoes,
          classificacao: "gold" as const,
        },
      },
      worst_post: {
        post_id: `${profile.handle}_worst`,
        permalink: `https://instagram.com/${profile.handle}`,
        thumb_url: `https://picsum.photos/seed/${profile.handle}worst/400/400`,
        caption_preview: d.worst_caption,
        metrics: {
          likes: d.worst_likes,
          comments: d.worst_comments,
          views: d.worst_views,
          engagement_score: d.worst_engagement / 100,
        },
        tier: "bronze" as const,
        analysis: {
          resumo_desempenho: d.worst_resumo,
          fatores_positivos: d.worst_positivos,
          fatores_negativos: d.worst_negativos,
          analise_gancho: d.worst_gancho,
          analise_legenda: d.worst_legenda,
          analise_formato: d.worst_formato,
          analise_hashtags: d.worst_hashtags,
          rubrica: d.worst_rubrica,
          nota_geral: d.worst_score,
          recomendacoes: d.worst_recomendacoes,
          classificacao: "bronze" as const,
        },
      },
      next_post_suggestion: {
        format: d.next_format,
        hook: d.next_hook,
        outline: d.next_outline,
        cta: d.next_cta,
        angle: d.next_angle,
      },
    },
    limits: { posts_analyzed: 9, note: "Análise demonstrativa" },
    plan: "free",
  };
}

function buildFallbackResult(profile: ShowcaseProfile): AnalysisResult {
  return {
    profile: {
      handle: profile.handle,
      full_name: profile.name,
      avatar_url: profile.avatar_url,
      bio_text: `${profile.name} | ${profile.nicheLabel}`,
      followers: profile.followers,
      following: 500,
      posts_count: 2000,
      is_verified: profile.is_verified,
    },
    deliverables: {
      bio_suggestion: {
        current_bio: `${profile.name} | ${profile.nicheLabel}`,
        suggested_bio: `${profile.name} | Referência em ${profile.nicheLabel}`,
        rationale_short: "Bio pode ser otimizada para melhor conversão.",
        cta_option: "",
        score: 5,
        score_new: 8,
        criteria: { clarity: 3, authority: 3, cta: 2, seo: 2, brand_voice: 3, specificity: 2 },
        criteria_new: { clarity: 5, authority: 5, cta: 4, seo: 4, brand_voice: 5, specificity: 4 },
        diagnostic: {
          proposta_valor: "A bio atual não comunica proposta de valor clara.",
          segmentacao_publico: "Sem segmentação visível de público-alvo.",
          gatilhos_autoridade: "Faltam gatilhos de autoridade e prova social.",
          cta_conversao: "Sem CTA para conversão de visitantes.",
          seo_instagram: "Faltam keywords para descoberta via busca.",
          tom_de_voz: "Tom pode ser melhor alinhado ao posicionamento.",
        },
        strengths: "Perfil com boa presença digital.",
        improvements: "Oportunidades de otimização na bio e conteúdo.",
      },
      top_post: {
        post_id: `${profile.handle}_top`,
        permalink: `https://instagram.com/${profile.handle}`,
        thumb_url: `https://picsum.photos/seed/${profile.handle}top/400/400`,
        caption_preview: "Conteúdo de alto engajamento deste perfil.",
        metrics: {
          likes: Math.round(profile.followers * (profile.engagement / 100) * 0.8),
          comments: Math.round(profile.followers * (profile.engagement / 100) * 0.05),
          views: Math.round(profile.followers * 0.3),
          engagement_score: profile.engagement / 100,
        },
        tier: "gold",
        analysis: {
          resumo_desempenho: "Post com alta performance no perfil.",
          fatores_positivos: ["Gancho chamativo", "Conteúdo relevante"],
          fatores_negativos: ["Poderia ter CTA mais claro"],
          analise_gancho: "Gancho eficaz que retém atenção.",
          analise_legenda: "Legenda bem estruturada.",
          analise_formato: "Formato adequado ao nicho.",
          analise_hashtags: "Hashtags poderiam ser mais nichadas.",
          rubrica: { gancho: 4, legenda: 4, formato: 4, engajamento: 4, estrategia: 3 },
          nota_geral: 7.5,
          recomendacoes: ["Adicionar CTA direto para aumentar interação"],
          classificacao: "gold",
        },
      },
      worst_post: {
        post_id: `${profile.handle}_worst`,
        permalink: `https://instagram.com/${profile.handle}`,
        thumb_url: `https://picsum.photos/seed/${profile.handle}worst/400/400`,
        caption_preview: "Post com menor engajamento do perfil.",
        metrics: {
          likes: Math.round(profile.followers * (profile.engagement / 100) * 0.15),
          comments: Math.round(profile.followers * (profile.engagement / 100) * 0.01),
          views: Math.round(profile.followers * 0.08),
          engagement_score: (profile.engagement / 100) * 0.2,
        },
        tier: "bronze",
        analysis: {
          resumo_desempenho: "Post com baixa performance.",
          fatores_positivos: ["Boa qualidade visual"],
          fatores_negativos: ["Sem gancho claro", "Caption genérica"],
          analise_gancho: "Sem gancho para reter atenção.",
          analise_legenda: "Caption genérica sem valor.",
          analise_formato: "Formato com baixa distribuição.",
          analise_hashtags: "Hashtags genéricas sem impacto.",
          rubrica: { gancho: 2, legenda: 2, formato: 2, engajamento: 2, estrategia: 2 },
          nota_geral: 3.0,
          recomendacoes: ["Adicionar storytelling e contexto ao post"],
          classificacao: "bronze",
        },
      },
      next_post_suggestion: {
        format: "Reels",
        hook: "O erro que todo mundo comete no Instagram",
        outline: ["Apresentar o erro", "Mostrar a consequência", "Dar a solução"],
        cta: "Salva esse post e aplica hoje",
        angle: "Conteúdo educativo",
      },
    },
    limits: { posts_analyzed: 9, note: "Análise demonstrativa" },
    plan: "free",
  };
}
