// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glgocjuwmssnaztljdus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsZ29janV3bXNzbmF6dGxqZHVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1MjU4MDIsImV4cCI6MjA4NzEwMTgwMn0.csxQ7SNsjkLEi8ygxj8TP3CzIg-L6An6RVSCwbXay4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});